name: offline_webview
description: A lightweight high-performance Flutter SDK for offline web package loading with URL matching, flow pipeline, WebView integration, monitoring and reporting. Supports iOS/Android.
homepage: https://github.com/rgmyyw/offline_webview
version: 1.1.1

environment:
  sdk: ^3.11.0
  flutter: ">=3.41.9"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1
  path_provider: ^2.1.5
  archive: ^4.0.9
  http: ^1.6.0
  flutter_inappwebview: ^6.1.5
  mime: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0
